// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210901101029_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("API.Entities.Zaposlenik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrojDanaGodisnjegOdmora")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrojDanaPlacenogDopusta")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrojSlobodnihDana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GodinaRodenja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Odjel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PocetakRada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slika")
                        .HasColumnType("TEXT");

                    b.Property<string>("Spol")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrajanjeUgovora")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VrstaUgovora")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zaposlenici");
                });
#pragma warning restore 612, 618
        }
    }
}
